export const SET_USER_SELECTED_DIRECTION = 'SET_USER_SELECTED_DIRECTION'
export const SET_USER_SELECTED_HIGHWAY = 'SET_USER_SELECTED_HIGHWAY'
export const SET_SELECTED_STATION_INFO = 'SET_SELECTED_STATION_INFO'
export const SET_STATIONS = 'SET_STATIONS'
