export const SET_USER_SELECTED_DIRECTION = 'SET_USER_SELECTED_DIRECTION'
export const SET_USER_SELECTED_HIGHWAY = 'SET_USER_SELECTED_HIGHWAY'
export const SET_SELECTED_STATION = 'SET_SELECTED_STATION'
export const SET_STATIONS = 'SET_STATIONS'
export const SET_AMOUNT_PREDICT_BARCHART_ACTIVEID =
  'SET_AMOUNT_PREDICT_BARCHART_ACTIVEID'
